<?php
// セレクトボックス
$Log_Before = [
   // 社員管理ページの更新
   ['soshiki_ID', 0, '', '組織名'],
   ['soshiki_ID', 1, '税理士法人○○', '組織名'],
   ['soshiki_ID', 2, '株式会社○○', '組織名'],
   ['soshiki_ID', 3, '株式会社○○○○', '組織名'],
   ['soshiki_ID', 4, '○○行政書士事務所', '組織名'],
   ['soshiki_ID', 5, '社会保険労務士法人○○', '組織名'],
   ['soshiki_ID', 6, '株式会社×××', '組織名'],
   ['ka_ID', 0, '', '課名'],
   ['ka_ID', 1, '１課', '課名'],
   ['ka_ID', 2, '２課', '課名'],
   ['ka_ID', 3, '３課', '課名'],
   ['ka_ID', 4, '経営戦略家', '課名'],
   ['bu_ID', 0, '', '部署名'],
   ['bu_ID', 1, '代表', '部署名'],
   ['bu_ID', 2, '相談役', '部署名'],
   ['bu_ID', 11, '○○', '部署名'],
   ['bu_ID', 12, '■■', '部署名'],
   ['bu_ID', 13, '@@@', '部署名'],
   ['bu_ID', 14, '!!!', '部署名'],
   ['bu_ID', 16, '++', '部署名'],
   ['bu_ID', 17, '「「「「「', '部署名'],
   ['bu_ID', 18, 'ｄｄｄｄ', '部署名'],
   ['bu_ID', 99, 'ああああ', '部署名'],
   ['bu_ID', 15, 'ｃｃｃ', '部署名'],
   ['bu_ID', 19, 'ｖｖｖ', '部署名'],
   ['bu_ID', 20, 'ｓｓｓｓｓ', '部署名'],
   ['bu_ID', 21, 'ｂｂｂｂ', '部署名'],
   ['bu_ID', 50, 'ｄｆｄｆｓｓｄｆ', '部署名'],
   ['bu_ID', 60, 'リフレ', '部署名'],
   ['yakushoku_id', 0, '', '役職名'],
   ['yakushoku_id', 1, '相談役', '役職名'],
   ['yakushoku_id', 2, '会長', '役職名'],
   ['yakushoku_id', 3, '代表', '役職名'],
   ['yakushoku_id', 4, '支社長', '役職名'],
   ['yakushoku_id', 5, '専務', '役職名'],
   ['yakushoku_id', 6, '常務', '役職名'],
   ['yakushoku_id', 7, '部長', '役職名'],
   ['yakushoku_id', 8, '次長', '役職名'],
   ['yakushoku_id', 9, '課長', '役職名'],
   ['yakushoku_id', 10, '係長', '役職名'],
   ['yakushoku_id', 11, '主任', '役職名'],
   ['yakushoku_id', 12, '一般', '役職名'],
   ['yakushoku_id', 13, 'パート', '役職名'],
   ['yakushoku_id', 14, '外注', '役職名'],
   ['yakushoku_id', 15, '室長', '役職名'],
   ['yakushoku_id', 16, '理事', '役職名'],
   ['yakushoku_id', 17, '理事長', '役職名'],
   ['yakushoku_id', 18, '常務理事', '役職名'],
   ['yakushoku_id', 19, '監事', '役職名'],
   ['yakushoku_id', 20, '代表取締役', '役職名'],
   ['yakushoku_id', 21, '社長', '役職名'],
   ['yakushoku_id', 22, '理事', '役職名'],
   ['yakushoku_id', 23, '副社長', '役職名'],
   ['yakushoku_id', 24, '理事長', '役職名'],
   ['yakushoku_id', 25, '常務理事', '役職名'],
   ['shainkubun_ID', 0, '', '社員区分'],
   ['shainkubun_ID', 1, '正社員', '社員区分'],
   ['shainkubun_ID', 2, '短時間正社員', '社員区分'],
   ['shainkubun_ID', 3, 'パート', '社員区分'],
   ['gakureki_id', 0, '', '学歴'],
   ['gakureki_id', 1, '大学院', '学歴'],
   ['gakureki_id', 2, '大学', '学歴'],
   ['gakureki_id', 3, '短大', '学歴'],
   ['gakureki_id', 4, '専門学校', '学歴'],
   ['gakureki_id', 5, '高校', '学歴'],
   ['gakureki_id', 5, '高校', '学歴'],
];

// 以外
$Log_Before_etc = [
   'sei' => '社員氏名(姓)',
   'mei' => '社員氏名(名)',
   'sei_kana' => '社員氏名(セイ)',
   'mei_kana' => '社員氏名(メイ)',
   'desknets_name' => 'コード名',
   'tel_main' => '電話番号',
   'tel_sub' => '電話番号２',
   'mail' => 'メールアドレス',
   'nyusha_nengapi' => '入社年月日',
   'taisha_nengapi' => '退社年月日',
   'seinengapi' => '生年月日',
   'sikaku1' => '資格１',
   'sikaku2' => '資格２',
   'sikaku3' => '資格３',
   'sikaku4' => '資格４',
   'sikaku5' => '資格５',
   'sotugyoko' => '卒業校',
   'biko' => '備考'
];

$select_option_komoku = array(
   'shain_ID' => '社員ID',
   'sei' => '姓',
   'mei' => '名',
   'sei_kana' => 'セイ',
   'mei_kana' => 'メイ',
   'desknetsname' => '名',
   'shoshiki_name' => '組織名',
   'ka_name' => '課名',
   'busho_name' => '部署名',
   'buka_name' => '部課名',
   'yakushoku_name' => '役職名',
   'shain_kubun' => '社員区分',
   'tel_no_main' => '電話番号',
   'tel_no_sub' => '電話番号２',
   'nyusha_day' => '入社年月日',
   'taisha_day' => '退社年月日',
   'Birth_day' => '生年月日',
   'seibetu' => '性別',
   'shikaku' => '資格',
   'gakureki' => '学歴',
   'sotugyoko' => '卒業校',
   'biko' => '備考'
);

$OPtion_Tag = array(
   'soshiki_ID',
   'ka_ID',
   'bu_ID',
   'yakushoku_id',
   'yakushoku_id',
   'shainkubun_ID',
   'gakureki_id'
);


$select_option_komoku_th = array(
   'shain_ID' => '社員ID',
   'sei' => '社員氏名',
   'shoshiki_name' => '組織名',
   'busho_name' => '部署名',
   'ka_name' => '課名',
   'yakushoku_name' => '役職名',
   'shain_kubun' => '社員区分',
   'nyusha_day' => '入社年月日',
   'taisha_day' => '退社年月日',
   'Birth_day' => '生年月日',
   'seibetu' => '性別',
   'shikaku1' => '資格1',
   'shikaku2' => '資格2',
   'shikaku3' => '資格3',
   'shikaku4' => '資格4',
   'shikaku5' => '資格5',
   'gakureki' => '学歴',
   'sotugyoko' => '卒業校',
);
